apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: p48tpciol-nodejs-gitops
  description: This is GitOps manifest for p48tpciol-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=p48tpciol-nodejs
    backstage.io/kubernetes-id: p48tpciol-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: p48tpciol-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:p48tpciol-nodejs
